### ISSUE TITLE
unable to use reflectable into my flutter project

### ISSUE THREAD

**Issue by maxime-aubry** [eernstg/reflectable-flutter#4]
Hello.

I try to use reflectable into my project.
`flutter doctor # just checking`
`flutter packages get`
`flutter packages pub run build_runner build`
`flutter create .`

when is use these command lines, a new file is created in my 'test' folder.
Why can't i get this one in my application ?

Thanks.

**Comment by eernstg** [comment]
I'm not quite sure what 'this one' is? The new file which is created is the "database" of entities that are needed in order to support reflective operations at the level that you've requested using capabilities, and that file would be imported by your entry point (that is, the library that contains `main` and imports everything else needed by the program).

The generated file is placed together with the entry point, so the reflectable builder is generating this database for an entry point in test, which means that this was the target that `build` handed to reflectable. That target would again have been selected based on your `build.yaml` file and the command line (and if this is `flutter packages pub run build_runner build` it should be determined by `build.yaml` alone).

My best guess at this point is: Check out the [information about `build.yaml`](https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md) in the build package and make sure it generates for the right target.

**Comment by maxime-aubry** [comment]
Hello.
I tried to get the file main.reflectable.dart
But i failed. Indeed I forgot to create a build.yaml file to complete the process.
Thanks a lot for your reply.

**Comment by eernstg** [comment]
Thanks!
